//jquery for onload
$(function() {
  memory = new Memory();
  registers = new Registers();
  code = new Code();
  tutorials = new Tutorials();
  var currTutorial = 0;

//number textfield lines
	$('.lined').linedtextarea(
		{selectedLine: 1}
	);
//display tutorial tabs and first first page of first tutorial
//tutorials.displayTabs
  tutorials.displayTutorial(0);

  //lISTENERS
  $('textarea#mainText').keyup(function(e) {
    if(e.keyCode == 13){
      //might use for parsing on enter
    }
  });

  updateRegs();

  $('button#parseButton').click(parseButton);
  $('button#updateRegsButton').click(updateRegs);
  $('button#runButton').click(runButton);
  $('button#answerButton').click(function(){tutorials.displayAnswer()});
  $('button#nextPageButton').click(tutorials.displayLastPage);


// remove this later. this code will be generated by js eventually
  $('#tutorial1').click(tutorials.displayNextPage);

});

// updates contents of registers
function updateRegs() {
    console.log("updating register contents");
    $("#registers").css("border","3px solid red");
    
    var registerValues = registers.getAll(); 

    for (var reg in registerValues) {
        $("#" + reg).text(registerValues[reg]);
    }
}

function parseButton() {
  var text = $('textarea#mainText').val();
  code.init(text);
}

function runButton() {
  parseButton();
  code.run();
}

function updateDisplay() {
  updateRegs();
  updateCurLine();
}

function updateCurLine() {
  $('#lineInfo').text("Current line: " + code.curLineNum());
}

//TODO: need some way to discard blank lines
/*function getLastLine() {
  var text = $('textarea#mainText').val();
  if (text == '') return '';
  var lines = text.split('\n'); 
  console.log(lines);
  if (lines.length <= 1) return '';
  return lines[lines.length - 2];
}*/

/*$('textarea#mainText').keyup(function() {
  console.log('Handler for .keyup() called.');
});*/
